<?php namespace App;

/**
 * Eloquent class to describe the failed_jobs table
 *
 * automatically generated by ModelGenerator.php
 */
class FailedJobs extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'failed_jobs';

    public $timestamps = false;

    protected $fillable = ['connection', 'queue', 'payload', 'exception', 'failed_at'];

    public function getDates()
    {
        return ['failed_at'];
    }
}
