<?php namespace App;

/**
 * Eloquent class to describe the films table
 *
 * automatically generated by ModelGenerator.php
 */
class Films extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'films';

    protected $fillable = ['titre', 'auteur', 'genre', 'duree', 'annee', 'img', 'synopsys'];

    public function getDates()
    {
        return ['annee'];
    }

    public function immatriculations()
    {
        return $this->hasMany('App\Immatriculations', 'films_id', 'id');
    }
}
